/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RSVPRecord = IDL.Record({
  'guestCount' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'dietary' : IDL.Text,
  'songRequest' : IDL.Text,
});
export const RSVPSubmission = IDL.Record({
  'guestCount' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'dietary' : IDL.Text,
  'songRequest' : IDL.Text,
});

export const idlService = IDL.Service({
  'getRSVPs' : IDL.Func([], [IDL.Vec(RSVPRecord)], ['query']),
  'submitRSVP' : IDL.Func(
      [RSVPSubmission],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RSVPRecord = IDL.Record({
    'guestCount' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'dietary' : IDL.Text,
    'songRequest' : IDL.Text,
  });
  const RSVPSubmission = IDL.Record({
    'guestCount' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'dietary' : IDL.Text,
    'songRequest' : IDL.Text,
  });
  
  return IDL.Service({
    'getRSVPs' : IDL.Func([], [IDL.Vec(RSVPRecord)], ['query']),
    'submitRSVP' : IDL.Func(
        [RSVPSubmission],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };